services:
  - type: web
    name: plant-recommendation-system
    env: python
    buildCommand: pip install -r requirements.txt && python scripts/preprocess_plants.py
    startCommand: gunicorn run:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
